{{- define "secret-template" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ .namespace  }}

data:
  secretKey: {{ .value | b64enc }}
{{- end -}}

{{- define "secret-template-multiple" -}}
{{ $flattenList := values . }}
{{ $flatten := first $flattenList  }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ get $flatten "name" }}
  namespace: {{ get $flatten "namespace"  }}
data:
  secretKey: {{  get $flatten "secret" |  b64enc }}
{{ print "---" -}}
{{ end -}}
